version: "3"

services:
    api:
        container_name: lapisco_fastAPI_GloboPlay
        command: "uvicorn app:app --host 0.0.0.0 --port $PORT"
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8000:$PORT
        env_file: .env
        restart: always