version: "3"

services:
    api:
        
        container_name: api_iris_django2.0
        command: "python manage.py runserver 0.0.0.0:8000"
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8000:8000
        env_file: iris_project/.env
        
        restart: always